export const CREATE_LEAVE = 'CREATE_LEAVE';
export const UPDATE_LEAVE = 'UPDATE_LEAVE';
export const DELETE_LEAVE = 'DELETE_LEAVE';
export const FETCH_ALL_LEAVE = 'FETCH_ALL_LEAVE';
export const FETCH_ONE_LEAVE = 'FETCH_ONE_LEAVE';
export const FETCH_LEAVE_BY_DATERANGE_PERSONAL =
  'FETCH_LEAVE_BY_DATERANGE_PERSONAL';
export const FETCH_LEAVE_BY_DATERANGE = 'FETCH_LEAVE_BY_DATERANGE';
export const LEAVE_START_LOADING = 'LEAVE_START_LOADING';
export const LEAVE_END_LOADING = 'LEAVE_END_LOADING';
export const LEAVE_ERROR = 'LEAVE_ERROR';
export const LEAVE_SUCCESS = 'LEAVE_SUCCESS';
export const FETCH_LEAVE_REQUESTS = 'FETCH_LEAVE_REQUESTS';
export const FETCH_UPCOMING_LEAVE = 'FETCH_UPCOMING_LEAVE';
export const FETCH_LEAVE_HISTORY = 'FETCH_LEAVE_HISTORY';
export const FETCH_TODAY_LEAVE = 'FETCH_TODAY_LEAVE';

export const AUTH = 'AUTH';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const UPDATE_AUTH = 'UPDATE_AUTH';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const LOGOUT = 'LOGOUT';
export const AUTH_START_LOADING = 'AUTH_START_LOADING';
export const AUTH_END_LOADING = 'AUTH_END_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const FETCH_ALL_USER = 'FETCH_ALL_USER';
export const FETCH_ONE_USER = 'FETCH_ONE_USER';
export const USER_START_LOADING = 'USER_START_LOADING';
export const USER_END_LOADING = 'USER_END_LOADING';
export const USER_ERROR = 'USER_ERROR';
export const USER_SUCCESS = 'USER_SUCCESS';
export const FETCH_DEPT_USER = 'FETCH_DEPT_USER';

export const CREATE_DEPT = 'CREATE_DEPT';
export const UPDATE_DEPT = 'UPDATE_DEPT';
export const DELETE_DEPT = 'DELETE_DEPT';
export const FETCH_ALL_DEPT = 'FETCH_ALL_DEPT';
export const FETCH_ONE_DEPT = 'FETCH_ONE_DEPT';
export const DEPT_START_LOADING = 'DEPT_START_LOADING';
export const DEPT_END_LOADING = 'DEPT_END_LOADING';
export const DEPT_ERROR = 'DEPT_ERROR';
export const DEPT_SUCCESS = 'DEPT_SUCCESS';

export const CREATE_LEAVETYPE = 'CREATE_LEAVETYPE';
export const UPDATE_LEAVETYPE = 'UPDATE_LEAVETYPE';
export const DELETE_LEAVETYPE = 'DELETE_LEAVETYPE';
export const FETCH_ALL_LEAVETYPE = 'FETCH_ALL_LEAVETYPE';
export const FETCH_ONE_LEAVETYPE = 'FETCH_ONE_LEAVETYPE';
export const LEAVETYPE_START_LOADING = 'LEAVETYPE_START_LOADING';
export const LEAVETYPE_END_LOADING = 'LEAVETYPE_END_LOADING';
export const LEAVETYPE_ERROR = 'LEAVE_ERROR';
export const FETCH_LEAVE_COUNT = 'FETCH_LEAVE_COUNT';
export const LEAVETYPE_SUCCESS = 'LEAVE_SUCCESS';

export const CREATE_ROLE = 'CREATE_ROLE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';
export const FETCH_ALL_ROLE = 'FETCH_ALL_ROLE';
export const FETCH_ONE_ROLE = 'FETCH_ONE_ROLE';
export const ROLE_START_LOADING = 'ROLE_START_LOADING';
export const ROLE_END_LOADING = 'ROLE_END_LOADING';
export const ROLE_ERROR = 'ROLE_ERROR';
export const ROLE_SUCCESS = 'ROLE_SUCCESS';

export const CREATE_HOLIDAY = 'CREATE_HOLIDAY';
export const UPDATE_HOLIDAY = 'UPDATE_HOLIDAY';
export const DELETE_HOLIDAY = 'DELETE_HOLIDAY';
export const FETCH_ALL_HOLIDAY = 'FETCH_ALL_HOLIDAY';
export const FETCH_ONE_HOLIDAY = 'FETCH_ONE_HOLIDAY';
export const HOLIDAY_START_LOADING = 'HOLIDAY_START_LOADING';
export const HOLIDAY_END_LOADING = 'HOLIDAY_END_LOADING';
export const HOLIDAY_ERROR = 'HOLIDAY_ERROR';
export const HOLIDAY_SUCCESS = 'HOLIDAY_SUCCESS';
export const FETCH_HOLIDAY_BY_YEAR = 'FETCH_HOLIDAY_BY_YEAR';

export const CREATE_TRAINING = 'CREATE_TRAINING';
export const FETCH_ALL_TRAINING = 'FETCH_ALL_TRAINING';
export const FETCH_ONE_TRAINING = 'FETCH_ONE_TRAINING';
export const TRAINING_START_LOADING = 'TRAINING_START_LOADING';
export const TRAINING_END_LOADING = 'TRAINING_END_LOADING';
export const TRAINING_ERROR = 'TRAINING_ERROR';
export const TRAINING_SUCCESS = 'TRAINING_SUCCESS';
export const UPDATE_TRAINING = 'UPDATE_TRAINING';
export const LEAVE_TRAINING = 'LEAVE_TRAINING';
export const FETCH_EXT_TRAINING = 'FETCH_EXT_TRAINING';
export const UPDATE_TRAINING_STATUS = 'UPDATE_TRAINING_STATUS';
export const FETCH_EXT_TRAINING_HISTORY = 'FETCH_EXT_TRAINING_HISTORY';
export const FETCH_TRAINING_HISTORY = 'FETCH_TRAINING_HISTORY';
export const FETCH_UPCOMING_TRAINING = 'FETCH_UPCOMING_TRAINING';
export const FETCH_TODAY_TRAINING = 'FETCH_TODAY_TRAINING';
export const FETCH_TRAINING_COUNT = 'FETCH_TRAINING_COUNT';

export const CREATE_TRAININGPROGRESS = 'CREATE_TRAININGPROGRESS';
export const FETCH_ALL_TRAININGPROGRESS = 'FETCH_ALL_TRAININGPROGRESS';
export const FETCH_ONE_TRAININGPROGRESS = 'FETCH_ONE_TRAININGPROGRESS';
export const TRAININGPROGRESS_START_LOADING = 'TRAININGPROGRESS_START_LOADING';
export const TRAININGPROGRESS_END_LOADING = 'TRAININGPROGRESS_END_LOADING';
export const TRAININGPROGRESS_ERROR = 'TRAININGPROGRESS_ERROR';
export const TRAININGPROGRESS_SUCCESS = 'TRAININGPROGRESS_SUCCESS';
export const UPDATE_TRAININGPROGRESS = 'UPDATE_TRAININGPROGRESS';
export const LEAVE_TRAININGPROGRESS = 'LEAVE_TRAININGPROGRESS';
export const FETCH_DEPT_TRAININGPROGRESS = 'FETCH_DEPT_TRAININGPROGRESS';
export const FETCH_USER_TRAININGPROGRESS = 'FETCH_USER_TRAININGPROGRESS';
//
export const FETCH_EXT_TRAININGPROGRESS = 'FETCH_EXT_TRAININGPROGRESS';
export const UPDATE_TRAININGPROGRESS_STATUS = 'UPDATE_TRAININGPROGRESS_STATUS';
export const FETCH_EXT_TRAININGPROGRESS_HISTORY =
  'FETCH_EXT_TRAININGPROGRESS_HISTORY';
export const FETCH_TRAININGPROGRESS_HISTORY = 'FETCH_TRAININGPROGRESS_HISTORY';
export const FETCH_UPCOMING_TRAININGPROGRESS =
  'FETCH_UPCOMING_TRAININGPROGRESS';
export const FETCH_TODAY_TRAININGPROGRESS = 'FETCH_TODAY_TRAININGPROGRESS';

export const CREATE_POLICY = 'CREATE_POLICY';
export const UPDATE_POLICY = 'UPDATE_POLICY';
export const DELETE_POLICY = 'DELETE_POLICY';
export const FETCH_ALL_POLICY = 'FETCH_ALL_POLICY';
export const FETCH_POLICY_BY_DEPT = 'FETCH_POLICY_BY_DEPT';
export const FETCH_ONE_POLICY = 'FETCH_ONE_POLICY';
export const POLICY_START_LOADING = 'POLICY_START_LOADING';
export const POLICY_END_LOADING = 'POLICY_END_LOADING';
export const POLICY_ERROR = 'POLICY_ERROR';
export const POLICY_SUCCESS = 'POLICY_SUCCESS';

export const NOTIFICATION_START_LOADING = 'NOTIFICATION_START_LOADING';
export const NOTIFICATION_END_LOADING = 'NOTIFICATION_END_LOADING';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
export const FETCH_ALL_NOTIFICATION = 'FETCH_ALL_NOTIFICATION';
export const CLEAR_NOTIFICATION_BY_TYPE = 'CLEAR_NOTIFICATION_BY_TYPE';
export const SET_NOTIFICATION_READ = 'SET_NOTIFICATION_READ';
