export const CREATE_LEAVE = 'CREATE_LEAVE';
export const UPDATE_LEAVE = 'UPDATE_LEAVE';
export const DELETE_LEAVE = 'DELETE_LEAVE';
export const FETCH_ALL_LEAVE = 'FETCH_ALL_LEAVE';
export const FETCH_ONE_LEAVE = 'FETCH_ONE_LEAVE';
export const FETCH_LEAVE_BY_DATERANGE = 'FETCH_LEAVE_BY_DATERANGE';
export const LEAVE_START_LOADING = 'LEAVE_START_LOADING';
export const LEAVE_END_LOADING = 'LEAVE_END_LOADING';
export const LEAVE_ERROR = 'LEAVE_ERROR';
export const FETCH_LEAVE_REQUESTS = 'FETCH_LEAVE_REQUESTS';
export const FETCH_UPCOMING_LEAVE = 'FETCH_UPCOMING_LEAVE';
export const FETCH_LEAVE_HISTORY = 'FETCH_LEAVE_HISTORY';
export const FETCH_TODAY_LEAVE = 'FETCH_TODAY_LEAVE';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const AUTH_START_LOADING = 'AUTH_START_LOADING';
export const AUTH_END_LOADING = 'AUTH_END_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';

export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const FETCH_ALL_USER = 'FETCH_ALL_USER';
export const FETCH_ONE_USER = 'FETCH_ONE_USER';
export const USER_START_LOADING = 'USER_START_LOADING';
export const USER_END_LOADING = 'USER_END_LOADING';
export const USER_ERROR = 'USER_ERROR';
export const FETCH_DEPT_USER = 'FETCH_DEPT_USER';

export const CREATE_DEPT = 'CREATE_DEPT';
export const UPDATE_DEPT = 'UPDATE_DEPT';
export const DELETE_DEPT = 'DELETE_DEPT';
export const FETCH_ALL_DEPT = 'FETCH_ALL_DEPT';
export const FETCH_ONE_DEPT = 'FETCH_ONE_DEPT';
export const DEPT_START_LOADING = 'DEPT_START_LOADING';
export const DEPT_END_LOADING = 'DEPT_END_LOADING';
export const DEPT_ERROR = 'DEPT_ERROR';

export const CREATE_LEAVETYPE = 'CREATE_LEAVETYPE';
export const UPDATE_LEAVETYPE = 'UPDATE_LEAVETYPE';
export const DELETE_LEAVETYPE = 'DELETE_LEAVETYPE';
export const FETCH_ALL_LEAVETYPE = 'FETCH_ALL_LEAVETYPE';
export const FETCH_ONE_LEAVETYPE = 'FETCH_ONE_LEAVETYPE';
export const LEAVETYPE_START_LOADING = 'LEAVETYPE_START_LOADING';
export const LEAVETYPE_END_LOADING = 'LEAVETYPE_END_LOADING';
export const LEAVETYPE_ERROR = 'LEAVE_ERROR';

export const CREATE_ROLE = 'CREATE_ROLE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';
export const FETCH_ALL_ROLE = 'FETCH_ALL_ROLE';
export const FETCH_ONE_ROLE = 'FETCH_ONE_ROLE';
export const ROLE_START_LOADING = 'ROLE_START_LOADING';
export const ROLE_END_LOADING = 'ROLE_END_LOADING';
export const ROLE_ERROR = 'ROLE_ERROR';

export const CREATE_HOLIDAY = 'CREATE_HOLIDAY';
export const UPDATE_HOLIDAY = 'UPDATE_HOLIDAY';
export const DELETE_HOLIDAY = 'DELETE_HOLIDAY';
export const FETCH_ALL_HOLIDAY = 'FETCH_ALL_HOLIDAY';
export const FETCH_ONE_HOLIDAY = 'FETCH_ONE_HOLIDAY';
export const HOLIDAY_START_LOADING = 'HOLIDAY_START_LOADING';
export const HOLIDAY_END_LOADING = 'HOLIDAY_END_LOADING';
export const HOLIDAY_ERROR = 'HOLIDAY_ERROR';
export const FETCH_HOLIDAY_BY_YEAR = 'FETCH_HOLIDAY_BY_YEAR';

export const CREATE_TRAINING = 'CREATE_TRAINING';
export const FETCH_ALL_TRAINING = 'FETCH_ALL_TRAINING';
export const FETCH_ONE_TRAINING = 'FETCH_ONE_TRAINING';
export const TRAINING_START_LOADING = 'TRAINING_START_LOADING';
export const TRAINING_END_LOADING = 'TRAINING_END_LOADING';
export const TRAINING_ERROR = 'TRAINING_ERROR';
export const UPDATE_TRAINING = 'UPDATE_TRAINING';
export const LEAVE_TRAINING = 'LEAVE_TRAINING';
export const FETCH_EXT_TRAINING = 'FETCH_EXT_TRAINING';
export const UPDATE_TRAINING_STATUS = 'UPDATE_TRAINING_STATUS';
export const FETCH_EXT_TRAINING_HISTORY = 'FETCH_EXT_TRAINING_HISTORY';
export const FETCH_TRAINING_HISTORY = 'FETCH_TRAINING_HISTORY';
export const FETCH_UPCOMING_TRAINING = 'FETCH_UPCOMING_TRAINING';
export const FETCH_TODAY_TRAINING = 'FETCH_TODAY_TRAINING';

export const CREATE_TRAININGREQUEST = 'CREATE_TRAININGREQUEST';
export const FETCH_ALL_TRAININGREQUEST = 'FETCH_ALL_TRAININGREQUEST';
export const FETCH_ONE_TRAININGREQUEST = 'FETCH_ONE_TRAININGREQUEST';
export const TRAININGREQUEST_START_LOADING = 'TRAININGREQUEST_START_LOADING';
export const TRAININGREQUEST_END_LOADING = 'TRAININGREQUEST_END_LOADING';
export const TRAININGREQUEST_ERROR = 'TRAININGREQUEST_ERROR';
export const UPDATE_TRAININGREQUEST = 'UPDATE_TRAININGREQUEST';
export const LEAVE_TRAININGREQUEST = 'LEAVE_TRAININGREQUEST';
export const FETCH_EXT_TRAININGREQUEST = 'FETCH_EXT_TRAININGREQUEST';
export const UPDATE_TRAININGREQUEST_STATUS = 'UPDATE_TRAININGREQUEST_STATUS';
export const FETCH_EXT_TRAININGREQUEST_HISTORY =
  'FETCH_EXT_TRAININGREQUEST_HISTORY';
export const FETCH_TRAININGREQUEST_HISTORY = 'FETCH_TRAININGREQUEST_HISTORY';
export const FETCH_UPCOMING_TRAININGREQUEST = 'FETCH_UPCOMING_TRAININGREQUEST';
export const FETCH_TODAY_TRAININGREQUEST = 'FETCH_TODAY_TRAININGREQUEST';
